@Test_Proj_HostAddress = https://localhost:7046

POST {{Test_Proj_HostAddress}}/api/ingestion/forces
Accept: application/json

###

POST {{Test_Proj_HostAddress}}/api/ingestion/crimes
Content-Type: application/json
Accept: application/json

{
  "latitude": 53.8008,
  "longitude": -1.5491,
  "month": "2024-01"
}

###
