// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test_Proj.Persistence;

#nullable disable

namespace Test_Proj.Persistence.Migrations
{
    [DbContext(typeof(PoliceDbContext))]
    partial class PoliceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Test_Proj.Persistence.PoliceRecord", b =>
                {
                    b.Property<string>("Dataset")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Scope")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Dataset", "Scope", "Key");

                    b.HasIndex("Dataset", "Scope", "SourceId")
                        .IsUnique();

                    b.ToTable("PoliceRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_PoliceRecords_Dataset", "\"Dataset\" IN ('forces','crimes','stop-searches')");

                            t.HasCheckConstraint("CK_PoliceRecords_Times", "\"UpdatedAtUtc\" >= \"FirstSeenUtc\" AND \"LastSeenUtc\" >= \"UpdatedAtUtc\"");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
